require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdditionalAttributesController do

  # This should return the minimal set of attributes required to create a valid
  # AdditionalAttribute. As you add validations to AdditionalAttribute, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdditionalAttributesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all additional_attributes as @additional_attributes" do
      additional_attribute = AdditionalAttribute.create! valid_attributes
      get :index, {}, valid_session
      assigns(:additional_attributes).should eq([additional_attribute])
    end
  end

  describe "GET show" do
    it "assigns the requested additional_attribute as @additional_attribute" do
      additional_attribute = AdditionalAttribute.create! valid_attributes
      get :show, {:id => additional_attribute.to_param}, valid_session
      assigns(:additional_attribute).should eq(additional_attribute)
    end
  end

  describe "GET new" do
    it "assigns a new additional_attribute as @additional_attribute" do
      get :new, {}, valid_session
      assigns(:additional_attribute).should be_a_new(AdditionalAttribute)
    end
  end

  describe "GET edit" do
    it "assigns the requested additional_attribute as @additional_attribute" do
      additional_attribute = AdditionalAttribute.create! valid_attributes
      get :edit, {:id => additional_attribute.to_param}, valid_session
      assigns(:additional_attribute).should eq(additional_attribute)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AdditionalAttribute" do
        expect {
          post :create, {:additional_attribute => valid_attributes}, valid_session
        }.to change(AdditionalAttribute, :count).by(1)
      end

      it "assigns a newly created additional_attribute as @additional_attribute" do
        post :create, {:additional_attribute => valid_attributes}, valid_session
        assigns(:additional_attribute).should be_a(AdditionalAttribute)
        assigns(:additional_attribute).should be_persisted
      end

      it "redirects to the created additional_attribute" do
        post :create, {:additional_attribute => valid_attributes}, valid_session
        response.should redirect_to(AdditionalAttribute.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved additional_attribute as @additional_attribute" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdditionalAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:additional_attribute => { "name" => "invalid value" }}, valid_session
        assigns(:additional_attribute).should be_a_new(AdditionalAttribute)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdditionalAttribute.any_instance.stub(:save).and_return(false)
        post :create, {:additional_attribute => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested additional_attribute" do
        additional_attribute = AdditionalAttribute.create! valid_attributes
        # Assuming there are no other additional_attributes in the database, this
        # specifies that the AdditionalAttribute created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AdditionalAttribute.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => additional_attribute.to_param, :additional_attribute => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested additional_attribute as @additional_attribute" do
        additional_attribute = AdditionalAttribute.create! valid_attributes
        put :update, {:id => additional_attribute.to_param, :additional_attribute => valid_attributes}, valid_session
        assigns(:additional_attribute).should eq(additional_attribute)
      end

      it "redirects to the additional_attribute" do
        additional_attribute = AdditionalAttribute.create! valid_attributes
        put :update, {:id => additional_attribute.to_param, :additional_attribute => valid_attributes}, valid_session
        response.should redirect_to(additional_attribute)
      end
    end

    describe "with invalid params" do
      it "assigns the additional_attribute as @additional_attribute" do
        additional_attribute = AdditionalAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdditionalAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => additional_attribute.to_param, :additional_attribute => { "name" => "invalid value" }}, valid_session
        assigns(:additional_attribute).should eq(additional_attribute)
      end

      it "re-renders the 'edit' template" do
        additional_attribute = AdditionalAttribute.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdditionalAttribute.any_instance.stub(:save).and_return(false)
        put :update, {:id => additional_attribute.to_param, :additional_attribute => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested additional_attribute" do
      additional_attribute = AdditionalAttribute.create! valid_attributes
      expect {
        delete :destroy, {:id => additional_attribute.to_param}, valid_session
      }.to change(AdditionalAttribute, :count).by(-1)
    end

    it "redirects to the additional_attributes list" do
      additional_attribute = AdditionalAttribute.create! valid_attributes
      delete :destroy, {:id => additional_attribute.to_param}, valid_session
      response.should redirect_to(additional_attributes_url)
    end
  end

end
